def jump():
	targetPos4 = -30 / 180 * math.pi / 50
	targetPos5 = 30 / 180 * math.pi / 50
	if (i >= 400 and i <=450):
		p.setJointMotorControl2(bodyUniqueId=boxId,
			                  jointIndex=7,
		                      controlMode=p.POSITION_CONTROL,
		                      targetPosition = targetPos4 * (i -400),
		                      force = maxForce)
		p.setJointMotorControl2(bodyUniqueId=boxId,
			                  jointIndex=10,
		                      controlMode=p.POSITION_CONTROL,
		                      targetPosition = targetPos4 * (i -400),
		                      force = maxForce)
		p.setJointMotorControl2(bodyUniqueId=boxId,
				                  jointIndex=8,
			                      controlMode=p.POSITION_CONTROL,
			                      targetPosition = targetPos5 * (i -400),
			                      force = maxForce)
		p.setJointMotorControl2(bodyUniqueId=boxId,
				                  jointIndex=11,
			                      controlMode=p.POSITION_CONTROL,
			                      targetPosition = targetPos5 * (i -400),
			                      force = maxForce)
	
	# if (i >= 298 and i <=350):
	# 	p.setJointMotorControl2(bodyUniqueId=boxId,
	# 		                  jointIndex=8,
	# 	                      controlMode=p.POSITION_CONTROL,
	# 	                      targetPosition = 90 / 180 * math.pi,
	# 	                      force = maxForce)
	# 	p.setJointMotorControl2(bodyUniqueId=boxId,
	# 		                  jointIndex=11,
	# 	                      controlMode=p.POSITION_CONTROL,
	# 	                      targetPosition = 90 / 180 * math.pi,
	# 	                      force = maxForce)
	if (i >= 500 and i <=550):
		p.setJointMotorControl2(bodyUniqueId=boxId,
			                  jointIndex=8,
		                      controlMode=p.POSITION_CONTROL,
		                      targetPosition = 110 / 180 * math.pi,
		                      force = maxForce)
		p.setJointMotorControl2(bodyUniqueId=boxId,
			                  jointIndex=11,
		                      controlMode=p.POSITION_CONTROL,
		                      targetPosition =110 / 180 * math.pi,
		                      force = maxForce)

		p.setJointMotorControl2(bodyUniqueId=boxId,
			                  jointIndex=2,
		                      controlMode=p.POSITION_CONTROL,
		                      targetPosition = 70 / 180 * math.pi,
		                      force = maxForce)
		p.setJointMotorControl2(bodyUniqueId=boxId,
			                  jointIndex=5,
		                      controlMode=p.POSITION_CONTROL,
		                      targetPosition = 70 / 180 * math.pi,
		                      force = maxForce)
	if (i >= 560):
		p.setJointMotorControl2(bodyUniqueId=boxId,
		                  jointIndex=1,
	                      controlMode=p.POSITION_CONTROL,
	                      targetPosition = - 45 / 180 * math.pi,
	                      force = maxForce)
		p.setJointMotorControl2(bodyUniqueId=boxId,
		                  jointIndex=4,
	                      controlMode=p.POSITION_CONTROL,
	                      targetPosition = - 45 / 180 * math.pi,
	                      force = maxForce)
		p.setJointMotorControl2(bodyUniqueId=boxId,
			                  jointIndex=2,
		                      controlMode=p.POSITION_CONTROL,
		                      targetPosition = 60 / 180 * math.pi,
		                      force = maxForce)
		p.setJointMotorControl2(bodyUniqueId=boxId,
			                  jointIndex=5,
		                      controlMode=p.POSITION_CONTROL,
		                      targetPosition = 60 / 180 * math.pi ,
		                      force = maxForce)
		p.setJointMotorControl2(bodyUniqueId=boxId,
			                  jointIndex=8,
		                      controlMode=p.POSITION_CONTROL,
		                      targetPosition = 60 / 180 * math.pi ,
		                      force = maxForce)
		p.setJointMotorControl2(bodyUniqueId=boxId,
			                  jointIndex=11,
		                      controlMode=p.POSITION_CONTROL,
		                      targetPosition = 60/ 180 * math.pi ,
		                      force = maxForce)